import student
import teacher
import attendance_information
import employee_information
import info_search
import subject
import achievements
import alumni
import Test
import test1
import customerLiability
import Test2
import priority_table
import partner
